### PR TITLE
Add default agent_class attribute to agent instatiation

### LINKED ISSUE #174: reparse_args causes Agents that use it to crash
The recent addition of the [class_name attribute](https://github.com/simonsobs/ocs/blob/5c3325a4c3afed52b9c07d315dba4319a570b15c/ocs/ocs_agent.py#L40) in the base OCSAgent causes older Agents still using the deprecated [site_config.reparse_args](https://github.com/simonsobs/ocs/blob/5c3325a4c3afed52b9c07d315dba4319a570b15c/ocs/site_config.py#L520) method to crash on startup.

```
2020-09-30T14:39:22+0000 Traceback (most recent call last):
2020-09-30T14:39:22+0000   File "influxdb_publisher.py", line 291, in <module>
2020-09-30T14:39:22+0000     agent, runner = ocs_agent.init_site_agent(args)
2020-09-30T14:39:22+0000   File "/app/ocs/ocs/ocs_agent.py", line 42, in init_site_agent
2020-09-30T14:39:22+0000     class_name=getattr(args, 'agent_class'))
2020-09-30T14:39:22+0000 AttributeError: 'Namespace' object has no attribute 'agent_class'
```

Since this has been marked as deprecated for almost a year now, it's good motivation to remove all uses of `reparse_args` from Agents.

### PR DESCRIPTION
**Pull request by BrianJKoopman**
## Description

Very small change related to #174.

## Motivation and Context

fixes #174

## How Has This Been Tested?

Tested in isolated set of containers, one of which was the influxdb publisher which broke from #174 and is fixed by this change.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Unless I am preparing a release, I have opened this PR onto the `develop` branch.

### CODE REVIEW

**Comment by BrianJKoopman** [comment]
Small bug fix, self merging.
